GET http://localhost:8080
###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "monkey",
  "password": 1234
}
###
GET http://localhost:8080/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTkwNTQ3NjcsImlhdCI6MTY1OTAxMTU2N30.YFur6r4qiaXj_8G23ZNu8cJZJLAKqF7czD_oFf5XYmM
###
